<?xml version="1.0"?>
<!--URDF MODEL 13 DoFs-->
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="robot3dof" >

<xacro:property name="arm_length" value="2" />
<xacro:property name="vertebrae" value="5" />

<xacro:include filename="$(find high_dof_description)/urdf/antro3.xacro" />
<xacro:include filename="$(find high_dof_description)/urdf/mobile_base.xacro" />
<link name="world" />

<xacro:mobile_base mobile="false" parent="world" child="a_mount_flange"/>

<xacro:antro3 prefix="a_" joint_limited="true" upper_arm_length="${0.5*arm_length/vertebrae}"  forearm_length="${0.5*arm_length/vertebrae}"/>

<joint name="b_fixed" type="fixed">
  <origin xyz="0 0 0" rpy="0 0 0" />
  <parent link="a_flange" />
  <child link="b_mount_flange" />
</joint>
<xacro:antro3 prefix="b_" joint_limited="true" upper_arm_length="${0.5*arm_length/vertebrae}"  forearm_length="${0.5*arm_length/vertebrae}"/>

<joint name="c_fixed" type="fixed">
  <origin xyz="0 0 0" rpy="0 0 0" />
  <parent link="b_flange" />
  <child link="c_mount_flange" />
</joint>
<xacro:antro3 prefix="c_" joint_limited="true" upper_arm_length="${0.5*arm_length/vertebrae}"  forearm_length="${0.5*arm_length/vertebrae}"/>

<joint name="d_fixed" type="fixed">
  <origin xyz="0 0 0" rpy="0 0 0" />
  <parent link="c_flange" />
  <child link="d_mount_flange" />
</joint>
<xacro:antro3 prefix="d_" joint_limited="true" upper_arm_length="${0.5*arm_length/vertebrae}"  forearm_length="${0.5*arm_length/vertebrae}"/>

<joint name="e_fixed" type="fixed">
  <origin xyz="0 0 0" rpy="0 0 0" />
  <parent link="d_flange" />
  <child link="e_mount_flange" />
</joint>
<xacro:antro3 prefix="e_" joint_limited="true" upper_arm_length="${0.5*arm_length/vertebrae}"  forearm_length="${0.5*arm_length/vertebrae}"/>

<joint name="last_flange_joint" type="fixed">
  <origin xyz="0 0 0" rpy="0 0 0" />
  <parent link="e_flange" />
  <child link="flange" />
</joint>
<link name="flange"/>

<xacro:include filename="$(find high_dof_description)/urdf/roscontrol.gazebo" />

</robot>
