<?xml version="1.0"?>
<!--URDF MODEL only arms-->
<robot xmlns:xacro="http://wiki.ros.org/xacro">
  <xacro:macro name="two_joints"
  params="joint_limited prefix upper_arm_length:=${0.35} upper_arm_radius:=${0.1} forearm_length:=${0.35} forearm_radius:=${0.1}">

    <link name="${prefix}mount_flange" >
<inertial>
  <mass value="0.01" />
  <origin xyz="0 0 0" rpy="0 0 0" />
  <inertia ixx="0.01" iyy="0.01" izz="0.01"
  ixy="0" ixz="0" iyz="0" />
</inertial>
</link>

<joint name="${prefix}joint_1" type="revolute">
  <origin xyz="0 0 0" rpy="${-pi*0.5} 0 0" />
  <parent link="${prefix}mount_flange" />
  <child link="${prefix}upper_arm_f1" />
  <dynamics damping="0.1" friction="0.1" />
  <xacro:unless value="${joint_limited}">
    <limit effort="30000" velocity="1.0" lower="-3.1416"
    upper="3.1416" />
  </xacro:unless>
  <xacro:if value="${joint_limited}">
    <limit effort="30000" velocity="10.0" lower="-1.5708"
    upper="1.5708" />
  </xacro:if>
  <axis xyz="0 0 1" />
</joint>

<link name="${prefix}upper_arm_f1" >
<inertial>
  <mass value="0.01" />
  <origin xyz="0 0 0" rpy="0 0 0" />
  <inertia ixx="0.01" iyy="0.01" izz="0.01"
  ixy="0" ixz="0" iyz="0" />
</inertial>
</link>


<joint name="${prefix}joint_2" type="revolute">
  <origin xyz="0 0 0" rpy="0 0 0" />
  <parent link="${prefix}upper_arm_f1" />
  <child link="${prefix}upper_arm" />
  <dynamics damping="0.1" friction="0.1" />
  <xacro:unless value="${joint_limited}">
    <limit effort="30000" velocity="1.0" lower="-3.1416"
    upper="3.1416" />
  </xacro:unless>
  <xacro:if value="${joint_limited}">
    <limit effort="30000" velocity="10.0" lower="-1.5708"
    upper="1.5708" />
  </xacro:if>
  <axis xyz="1 0 0" />
</joint>

<link name="${prefix}upper_arm">
  <inertial>
    <mass value="${6.5*upper_arm_length}" />
    <origin xyz="0 0 0" rpy="0 0 0" />
    <inertia ixx="0.019063" iyy="0.0013033" izz="0.019063"
    ixy="0" ixz="0" iyz="0" />
  </inertial>
  <visual>
    <origin xyz="0 ${-upper_arm_length/2} 0" rpy="1.5708 0 0" />
    <geometry>
      <cylinder length="${upper_arm_length}"
      radius="${upper_arm_radius}" />
    </geometry>
    <material name="blue">
      <color rgba="0.0 0.0 0.8 1.0" />
    </material>
  </visual>
  <collision>
    <origin xyz="0 ${-upper_arm_length/2} 0" rpy="1.5708 0 0" />
    <geometry>
      <cylinder length="${-upper_arm_length}"
      radius="${upper_arm_radius}" />
    </geometry>
  </collision>
</link>

<joint name="${prefix}joint_3" type="fixed">
  <origin xyz="0 ${-upper_arm_length} 0" rpy="0 0 0" />
  <parent link="${prefix}upper_arm" />
  <child link="${prefix}forearm" />
  <dynamics damping="0.1" friction="0.1" />
  <xacro:unless value="${joint_limited}">
    <limit effort="30000" velocity="1.0" lower="-3.1416"
    upper="3.1416" />
  </xacro:unless>
  <xacro:if value="${joint_limited}">
    <limit effort="30000" velocity="10.0" lower="-1.5708"
    upper="1.5708" />
  </xacro:if>
  <axis xyz="1 0 0" />
</joint>

    <link name="${prefix}forearm">
      <inertial>
        <mass value="${5.2*forearm_length}" />
        <origin xyz="0 0 0" rpy="0 0 0" />
        <inertia ixx="0.0084595" iyy="0.00038616" izz="0.0084595"
        ixy="0" ixz="0" iyz="0" />
      </inertial>
      <visual>
        <origin xyz="0 ${-forearm_length/2} 0" rpy="1.5708 0 0" />
        <geometry>
          <cylinder length="${forearm_length}"
          radius="${forearm_radius}" />
        </geometry>
        <material name="grey">
          <color rgba="0.8 0.8 0.8 1.0" />
        </material>
      </visual>
      <collision>
        <origin xyz="0 ${-forearm_length/2} 0" rpy="1.5708 0 0" />
        <geometry>
          <cylinder length="${forearm_length}"
          radius="${forearm_radius}" />
        </geometry>
      </collision>
    </link>



    <joint name="${prefix}elbow_joint" type="fixed">
      <origin xyz="0 ${-forearm_length} 0" rpy="${pi*0.5} 0 0" />
      <parent link="${prefix}forearm" />
      <child link="${prefix}flange" />
    </joint>

<link name="${prefix}flange">
<inertial>
  <mass value="0.01" />
  <origin xyz="0 0 0" rpy="0 0 0" />
  <inertia ixx="0.01" iyy="0.01" izz="0.01"
  ixy="0" ixz="0" iyz="0" />
</inertial>
</link>


<transmission name="${prefix}tran_1">
  <type>transmission_interface/SimpleTransmission</type>
  <joint name="${prefix}joint_1">
    <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
  </joint>
  <actuator name="${prefix}motor_1">
    <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    <mechanicalReduction>1</mechanicalReduction>
  </actuator>
</transmission>

<transmission name="${prefix}tran_2">
  <type>transmission_interface/SimpleTransmission</type>
  <joint name="${prefix}joint_2">
    <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
  </joint>
  <actuator name="${prefix}motor_2">
    <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    <mechanicalReduction>1</mechanicalReduction>
  </actuator>
</transmission>



<xacro:include filename="$(find high_dof_description)/urdf/antro3.gazebo" />

</xacro:macro>

</robot>
