controller_list:
  - name: fake_manipulator_controller
    type: $(arg fake_execution_type)
    joints:
      - a_joint_1
      - a_joint_2
      - a_joint_3
      - b_joint_1
      - b_joint_2
      - b_joint_3
      - c_joint_1
      - c_joint_2
      - c_joint_3
      - d_joint_1
      - d_joint_2
      - d_joint_3
      - e_joint_1
      - e_joint_2
      - e_joint_3
initial:  # Define initial robot poses per group
  - group: manipulator
    pose: home