test_name: "portal"

group_name: imm1
pipeline_ids:
- dirrt
planner_ids:
  dirrt:
  - imm1_mixed_strategy_a
  #- imm1_mixed_strategy_b
  - imm1_informed_rrt
  - imm1_warp_strategy


planning_time:  600.0
long_planning_time:  900.0 # first repetition planning time

queries_number: 1
query_prefix: portal
scenarios: [portal]
repetitions: 30
starting_query: 0

# scenarios
portal:
  object_groups: ["portal"]
  query_0:
    goal_configurations:
    - [0, 6.5, 1.57079632679,  0, 0, 0,  0, 0, 0]
    start_configuration: [0, 3.5, 1.57079632679,  0, 0, 0,  0, 0, 0]
