test_name: "wide_portal"

group_name: imms
pipeline_ids:
- dirrt
planner_ids:
  dirrt:
  - imms_mixed_strategy_a
  #- imm1_mixed_strategy_b
  - imms_informed_rrt
  - imms_warp_strategy


planning_time:  752 #3620.0 #3600.0
long_planning_time:  752 #3620.0 #3600.0 # first repetition planning time

queries_number: 1
query_prefix: two_portals
scenarios: [two_portals]
repetitions: 10
starting_query: 0

# scenarios
portal:
  object_groups: ["portal"]
  query_0:
    goal_configurations:
    - [                   0, 3.5, 1.57079632679,  0, 0, 0, 0, 0, 0,  8.5, 1.5, 1.57079632679,  0, 0, 0,  0, 0, 0]
    start_configuration: [0, 3.5, 1.57079632679,  0, 0, 0, 0, 0, 0,  8.5, 1.5, 1.57079632679,  0, 0, 0,  0, 0, 0]


two_portals:
  object_groups: ["two_portals2"]
  query_0:
    goal_configurations:
    - [                   0, 3, 1.57079632679,  0, 0, 0, 0, 0, 0,  0, 3, 1.57079632679,  0, 0, 0,  0, 0, 0]
    start_configuration: [0, 0, 1.57079632679,  0, 0, 0, 0, 0, 0,  0, 0, 1.57079632679,  0, 0, 0,  0, 0, 0]
