group_names_map:
  mixed_strategy: manipulator



mixed_strategy:
  type: Multigoal
  max_distance: 0.2
  max_refine_time: 1500.0
  extend: false
  local_bias: 0.25
  tube_radius: 0.02
  base_frame: world
  tool_frame: tip
  min_distance: 0.4
  max_distance: 1.0
  max_penalty: 10.0
  display_bubbles: true
  links:
  - tip
  - ur5_tool0
  - ur5_wrist_1_link
  - ur5_wrist_2_link
  - ur5_wrist_3_link
  - ur5_forearm_link
  - ur5_upper_arm_link

  use_avoidance_goal: false # set true if the human avoidance is done only at the goal. Useful in Multigoal planning. ***CHANGE IT***
  use_avoidance_path: false # set true if the human avoidance is done during the path. It is slower than use_avoidance_goal. ***CHANGE IT***
  #If use_avoidance_goal and use_avoidance_path are both true, use_avoidance_path is used.
  computation_step: 0.01
  detector_topic: /poses #topic name of the message type geometry_msgs/PoseArray. ***CHANGE IT IF NEEDED***


