group_names_map:
  mixed_strategy: manipulator
  mixed_strategy_extend: manipulator
  mixed_strategy_9901: manipulator
  mixed_strategy_extend_9901: manipulator
  mixed_strategy_9902: manipulator
  mixed_strategy_extend_9902: manipulator
  mixed_strategy_99902: manipulator
  mixed_strategy_99902b: manipulator
  mixed_strategy_99902c: manipulator
  mixed_strategy_99902d: manipulator
  mixed_strategy_99902e: manipulator
  mixed_strategy_extend_99902: manipulator
  informed_rrt: manipulator

default_planner_config: mixed_strategy


mixed_strategy:
  type: Multigoal
  max_distance: 0.5
  max_refine_time: 1500.0
  extend: false
  local_bias: 0.25
  forgetting_factor: 0.999
  tube_radius: 0.01
  utopia_tolerance: 0.0000001

mixed_strategy_extend:
  type: Multigoal
  max_distance: 0.5
  max_refine_time: 1500.0
  extend: true
  local_bias: 0.25
  forgetting_factor: 0.999
  tube_radius: 0.01
  utopia_tolerance: 0.0000001


mixed_strategy_9901:
  type: Multigoal
  max_distance: 0.5
  max_refine_time: 1500.0
  extend: false
  local_bias: 0.25
  forgetting_factor: 0.99
  tube_radius: 0.01
  utopia_tolerance: 0.0000001

mixed_strategy_extend_9901:
  type: Multigoal
  max_distance: 0.5
  max_refine_time: 1500.0
  extend: true
  local_bias: 0.25
  forgetting_factor: 0.99
  tube_radius: 0.01
  utopia_tolerance: 0.0000001


mixed_strategy_99902:
  type: Multigoal
  max_distance: 0.5
  max_refine_time: 1500.0
  rewire_radius: 1.0
  extend: false
  local_bias: 0.25
  forgetting_factor: 0.999
  tube_radius: 0.02
  utopia_tolerance: 0.0000001

mixed_strategy_99902b:
  type: Multigoal
  max_distance: 0.5
  max_refine_time: 1500.0
  rewire_radius: 2.0
  extend: true
  local_bias: 0.25
  forgetting_factor: 0.999
  tube_radius: 0.02
  utopia_tolerance: 0.0000001

mixed_strategy_99902c:
  type: Multigoal
  max_distance: 0.1
  max_refine_time: 1500.0
  rewire_radius: 2.0
  extend: true
  local_bias: 0.25
  forgetting_factor: 0.999
  tube_radius: 0.02
  utopia_tolerance: 0.0000001

mixed_strategy_99902e:
  type: Multigoal
  max_distance: 1.0
  max_refine_time: 1500.0
  rewire_radius: 1.0
  extend: true
  local_bias: 0.25
  forgetting_factor: 0.999
  tube_radius: 0.02
  utopia_tolerance: 0.0000001

mixed_strategy_99902d:
  type: Multigoal
  max_distance: 0.5
  max_refine_time: 1500.0
  rewire_radius: 0.5
  extend: true
  local_bias: 0.25
  forgetting_factor: 0.999
  tube_radius: 0.02
  utopia_tolerance: 0.0000001

mixed_strategy_extend_99902:
  type: Multigoal
  max_distance: 0.5
  max_refine_time: 1500.0
  rewire_radius: 1.0
  extend: true
  local_bias: 0.25
  forgetting_factor: 0.999
  tube_radius: 0.02
  utopia_tolerance: 0.0000001

mixed_strategy_9902:
  type: Multigoal
  max_distance: 0.5
  max_refine_time: 1500.0
  extend: false
  local_bias: 0.25
  forgetting_factor: 0.99
  tube_radius: 0.02
  utopia_tolerance: 0.0000001

mixed_strategy_extend_9902:
  type: Multigoal
  max_distance: 0.5
  max_refine_time: 1500.0
  rewire_radius: 1.0
  extend: true
  local_bias: 0.25
  forgetting_factor: 0.99
  tube_radius: 0.02
  utopia_tolerance: 0.0000001


informed_rrt:
  type: Multigoal
  max_distance: 0.5
  max_refine_time: 1500.0
  extend: true
  local_bias: 0.0
  forgetting_factor: 0
  tube_radius: 0.01
  utopia_tolerance: 0.0000001
