controller_list:
  - name: manipulator
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
    - a_joint_1
    - a_joint_2
    - a_joint_3
    - b_joint_1
    - b_joint_2
    - b_joint_3
