scene_objects:
##- {type: "barra_testa", frame: "table", position: [0.80, 1.0, 0.9], quaternion: [0, 0, 0, 1]}
#- {type: "box_grigio", frame: "world", position: [0, 1.35,0], quaternion: [0, 0, 0, 1]}
#- {type: "box_grigio", frame: "world", position: [0,-1.35,0], quaternion: [0, 0, 0, 1]}
#- {type: "box_grigio", frame: "world", position: [ 1.35,0, 0], quaternion: [0, 0, 0, 1]}
#- {type: "box_grigio", frame: "world", position: [-1.35,0, 0], quaternion: [0, 0, 0, 1]}
- {type: "box_small", frame: "world", position: [1,0, 1], quaternion: [0, 0, 0, 1]}


box_grigio:
  color: [0.2,0.2,0.2, 1.]
  box:  [0.5,0.5,2.0]
  offset_quaternion: [ 0, 0, 0, 1 ]
  offset: [0, 0, 1.0]

box_small:
  color: [0.3,0.3,0.3, 1.0]
  box:  [0.2,0.2,1.0]
  offset_quaternion: [ 0, 0, 0, 1 ]
  offset: [0, 0, 0]
